---
- name: Install chocolate
  win_chocolatey:
    name: '{{ item }}'
    state: present
  with_items:
   - git
   - googlechrome
   - jre8
   - sikulix
   - notepadplusplus.install
   - git.install
   - dotnet4.5
   - conemu
   - awscli
   - sql-server-management-studio
   - psexec
   - openssh
  async: 60
  poll: 10
  ignore_errors: yes
